### ISSUE TITLE
Missing photo in the README

### ISSUE THREAD

**Issue by NdagiStanley** [akabiru/rafiki-zsh#11]
![screenshot 2018-09-20 17 06 32](https://user-images.githubusercontent.com/15629602/45823955-89d23980-bcf7-11e8-9a8e-0fd0174d61db.png)

The rafiki picture is missing

**Comment by akabiru** [comment]
Good eye @NdagiStanley. Are you able to resolve this? Probably a broken dropbox link. 🙈 Maybe we can store on GitHub?

**Comment by NdagiStanley** [comment]
PR is up.
